#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-vsftpd.json" ] && {
    cat > /usr/share/ucitrack/luci-app-vsftpd.json << EEOF
{
    "config": "vsftpd",
    "init": "vsftpd"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
EOF

rm -f /tmp/luci-vsftpd
exit 0
