#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-natter2.json" ] && {
    cat > /usr/share/ucitrack/luci-app-natter2.json << EEOF
{
    "config": "natter2",
    "init": "natter2"
}
EEOF
/etc/init.d/ucitrack reload
}

uci -q batch <<-EOF >/dev/null
EOF

exit 0
