#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-hypermodem.json" ] && {
    cat > /usr/share/ucitrack/luci-app-hypermodem.json << EEOF
{
    "config": "hypermodem",
    "init": "hypermodem"
}
EEOF
/etc/init.d/ucitrack reload
}

uci -q batch <<-EOF >/dev/null
EOF

rm -f /tmp/luci-indexcache
exit 0
