include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-guest-wifi

LUCI_TITLE:=LuCI support for guest-wifi
LUCI_DEPENDS:=+luci-base +luci-compat
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature