#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-frps.json" ] && {
    cat > /usr/share/ucitrack/luci-app-frps.json << EEOF
{
    "config": "frps",
    "init": "frps"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@frps[-1]
	add ucitrack frps
	set ucitrack.@frps[-1].init=frps
	commit ucitrack
EOF

rm -rf /tmp/luci-indexcache /tmp/luci-modulecache
exit 0
