#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-frps.json" ] && {
    cat > /usr/share/ucitrack/luci-app-frps.json << EEOF
{
    "config": "frps",
    "init": "frps"
}
EEOF
}
/etc/init.d/ucitrack reload

uci -q batch <<-EOF >/dev/null
EOF

rm -rf /tmp/luci-indexcache /tmp/luci-modulecache
exit 0
