#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-vsftpd.json" ] && {
    cat > /usr/share/ucitrack/luci-app-vsftpd.json << EEOF
{
    "config": "vsftpd",
    "init": "vsftpd"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@vsftpd[-1]
	add ucitrack vsftpd
	set ucitrack.@vsftpd[-1].init=vsftpd
	commit ucitrack
EOF

rm -f /tmp/luci-vsftpd
exit 0
