#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-wolplus.json" ] && {
    cat > /usr/share/ucitrack/luci-app-wolplus.json << EEOF
{
    "config": "wolplus",
    "init": "wolplus"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
EOF

rm -f /tmp/luci-indexcache
exit 0
