#!/bin/sh 
[ ! -f "/usr/share/ucitrack/luci-app-tencentddns.json" ] && {
    cat > /usr/share/ucitrack/luci-app-tencentddns.json << EEOF
{
    "config": "tencentddns",
    "init": "tencentddns"
}
EEOF
/etc/init.d/ucitrack reload
}

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@tencentddns[-1]
	add ucitrack tencentddns
	set ucitrack.@tencentddns[-1].init=tencentddns
	commit ucitrack
EOF

exit 0
