#!/bin/sh 
[ ! -f "/usr/share/ucitrack/luci-app-tencentddns.json" ] && {
    cat > /usr/share/ucitrack/luci-app-tencentddns.json << EEOF
{
    "config": "tencentddns",
    "init": "tencentddns"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
EOF

exit 0
