#!/bin/sh 
[ ! -f "/usr/share/ucitrack/luci-app-omr-tracker.json" ] && {
    cat > /usr/share/ucitrack/luci-app-omr-tracker.json << EEOF
{
    "config": "omr-tracker",
    "init": "omr-tracker"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@omr-tracker[-1]
	add ucitrack omr-tracker
	set ucitrack.@omr-tracker[-1].init=omr-tracker
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
