#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-spdmodem.json" ] && {
    cat > /usr/share/ucitrack/luci-app-spdmodem.json << EEOF
{
    "config": "spdmodem",
    "init": "spdmodem"
}
EEOF
/etc/init.d/ucitrack reload
}

uci -q batch <<-EOF >/dev/null
EOF

rm -f /tmp/luci-indexcache
exit 0
