include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for Nginx UI
LUCI_DEPENDS:=+subconverter +sub-web +luci-base
LUCI_PKGARCH:=all


include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
