#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-gecoosac.json" ] && {
    cat > /usr/share/ucitrack/luci-app-gecoosac.json << EEOF
{
    "config": "gecoosac",
    "init": "gecoosac"
}
EEOF
}
/etc/init.d/ucitrack reload

uci -q batch <<-EOF >/dev/null
EOF

rm -rf /tmp/luci-*
exit 0
