#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-eqosplus.json" ] && {
    cat > /usr/share/ucitrack/luci-app-eqosplus.json << EEOF
{
    "config": "eqosplus",
    "init": "eqosplus"
}
EEOF
}
chmod +x  /etc/init.d/eqosplus /usr/bin/eqosplus*
uci -q batch <<-EOF >/dev/null
EOF

[ -s /etc/config/eqosplus ] || echo "config eqosplus" > /etc/config/eqosplus

rm -f /tmp/luci-indexcache
exit 0
