#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-koolproxy.json" ] && {
    cat > /usr/share/ucitrack/luci-app-koolproxy.json << EEOF
{
    "config": "koolproxy",
    "init": "koolproxy"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
	delete firewall.koolproxy
	set firewall.koolproxy=include
	set firewall.koolproxy.type=script
	set firewall.koolproxy.path=/var/etc/koolproxy.include
	set firewall.koolproxy.reload=1
	commit firewall
EOF

rm -f /tmp/luci-indexcache
exit 0
