#!/bin/sh /etc/rc.common
# Copyright 2023-2026 sirpdboy team <herboy2008@gmail.com>

START=99

boot() {
    [ -x /usr/bin/kucat-config ] && /usr/bin/kucat-config
}

start() {
    [ -x /usr/bin/kucat-config ] && /usr/bin/kucat-config
}

restart() {
    [ -x /usr/bin/kucat-config ] && /usr/bin/kucat-config
}

reload() {
    # ÷ÿ‘ÿ≈‰÷√
    [ -x /usr/bin/kucat-config ] && /usr/bin/kucat-config
}
