#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-arpbind.json" ] && {
    cat > /usr/share/ucitrack/luci-app-arpbind.json << EEOF
{
    "config": "arpbind",
    "init": "arpbind"
}
EEOF
}
touch /etc/config/arpbind

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@arpbind[-1]
	add ucitrack arpbind
	set ucitrack.@arpbind[-1].init=arpbind
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
