#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-beardropper.json" ] && {
    cat > /usr/share/ucitrack/luci-app-beardropper.json << EEOF
{
    "config": "beardropper",
    "init": "beardropper"
}
EEOF
}
/etc/init.d/ucitrack reload

uci -q batch <<-EOF >/dev/null
EOF

rm -rf /tmp/luci-*
exit 0
