#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-dnscrypt_proxy.json" ] && {
    cat > /usr/share/ucitrack/luci-app-dnscrypt_proxy.json << EEOF
{
    "config": "dnscrypt_proxy",
    "init": "dnscrypt_proxy"
}
EEOF
}
/etc/init.d/ucitrack reload

uci -q batch <<-EOF >/dev/null
	delete firewall.dnscrypt_proxy
	set firewall.dnscrypt_proxy=include
	set firewall.dnscrypt_proxy.type=script
	set firewall.dnscrypt_proxy.path=/var/etc/dnscrypt-proxy.include
	set firewall.dnscrypt_proxy.reload=1
	commit firewall
EOF

rm -f /tmp/luci-indexcache
exit 0
