#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-k3screenctrl.json" ] && {
    cat > /usr/share/ucitrack/luci-app-k3screenctrl.json << EEOF
{
    "config": "k3screenctrl",
    "init": "k3screenctrl"
}
EEOF
/etc/init.d/ucitrack reload
}
uci -q batch <<-EOF >/dev/null
EOF
exit 0
