#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-aliyundrive-webdav.json" ] && {
    cat > /usr/share/ucitrack/luci-app-aliyundrive-webdav.json << EEOF
{
    "config": "aliyundrive-webdav",
    "init": "aliyundrive-webdav"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
EOF

rm -f /tmp/luci-indexcache
exit 0
