#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-wifidog.json" ] && {
    cat > /usr/share/ucitrack/luci-app-wifidog.json << EEOF
{
    "config": "wifidog",
    "init": "wifidog"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
EOF

rm -f /tmp/luci-indexcache
exit 0
