#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-AdGuardHome.json" ] && {
    cat > /usr/share/ucitrack/luci-app-AdGuardHome.json << EEOF
{
    "config": "AdGuardHome",
    "init": "AdGuardHome"
}
EEOF
/etc/init.d/ucitrack reload
}

uci -q batch <<-EOF >/dev/null 2>&1
	delete AdGuardHome.AdGuardHome.ucitracktest
EOF

rm -f /tmp/luci-indexcache
chmod +x /etc/init.d/AdGuardHome /usr/share/AdGuardHome/*

exit 0
