#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-nginx-manager.json" ] && {
    cat > /usr/share/ucitrack/luci-app-nginx-manager.json << EEOF
{
    "config": "nginx-manager",
    "init": "nginx-manager"
}
EEOF
/etc/init.d/ucitrack reload
}

uci -q batch <<-EOF >/dev/null
EOF

rm -f /tmp/luci-indexcache
exit 0
