#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-easymesh.json" ] && {
    cat > /usr/share/ucitrack/luci-app-easymesh.json << EEOF
{
    "config": "easymesh",
    "init": "easymesh"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@easymesh[-1]
	add ucitrack easymesh
	set ucitrack.@easymesh[-1].init=easymesh
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
