#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-mosdns.json" ] && {
    cat > /usr/share/ucitrack/luci-app-mosdns.json << EEOF
{
    "config": "mosdns",
    "init": "mosdns"
}
EEOF
}

[ -f "/etc/config/ucitrack" ] && {
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@mosdns[-1]
	add ucitrack mosdns
	set ucitrack.@mosdns[-1].init=mosdns
	commit ucitrack
EOF
}

rm -rf /tmp/luci-*
exit 0
