#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-mosdns.json" ] && {
    cat > /usr/share/ucitrack/luci-app-mosdns.json << EEOF
{
    "config": "mosdns",
    "init": "mosdns"
}
EEOF
/etc/init.d/ucitrack reload
}

[ -f "/etc/config/ucitrack" ] && {
uci -q batch <<-EOF >/dev/null
EOF
}

rm -rf /tmp/luci-*
exit 0
