#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-pikpak-webdav.json" ] && {
    cat > /usr/share/ucitrack/luci-app-pikpak-webdav.json << EEOF
{
    "config": "pikpak-webdav",
    "init": "pikpak-webdav"
}
EEOF
}
/etc/init.d/ucitrack reload

uci -q batch <<-EOF >/dev/null
EOF

rm -f /tmp/luci-indexcache
exit 0
