#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-pikpak-webdav.json" ] && {
    cat > /usr/share/ucitrack/luci-app-pikpak-webdav.json << EEOF
{
    "config": "pikpak-webdav",
    "init": "pikpak-webdav"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@pikpak-webdav[-1]
	add ucitrack pikpak-webdav
	set ucitrack.@pikpak-webdav[-1].init=pikpak-webdav
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
