#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-socat.json" ] && {
    cat > /usr/share/ucitrack/luci-app-socat.json << EEOF
{
    "config": "socat",
    "init": "socat"
}
EEOF
}

[ -f "/etc/config/ucitrack" ] && {
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@socat[-1]
	add ucitrack socat
	set ucitrack.@socat[-1].init=luci_socat
	commit ucitrack
EOF
}

rm -rf /tmp/luci-*cache*
exit 0
