#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-nezha-agent-v1.json" ] && {
    cat > /usr/share/ucitrack/luci-app-nezha-agent-v1.json << EEOF
{
    "config": "nezha-agent-v1",
    "init": "nezha-agent-v1"
}
EEOF
}

# 创建必要的配置文件和目录
mkdir -p /etc/config
touch /etc/config/nezha-agent-v1
touch /etc/config/nz.yml

# 设置基本配置
uci -q batch <<-EOF >/dev/null
	set nezha-agent-v1.config=config
	set nezha-agent-v1.config.enabled=0
	set nezha-agent-v1.config.server='THEBIGDICK'
	set nezha-agent-v1.config.client_secret=''
	set nezha-agent-v1.config.uuid=''
	set nezha-agent-v1.config.tls=0
	set nezha-agent-v1.config.insecure_tls=0
	commit nezha-agent-v1
EOF

# 添加服务跟踪
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@nezha-agent-v1[-1] 2>/dev/null
	add ucitrack nezha-agent-v1
	set ucitrack.@nezha-agent-v1[-1].init=nezha-agent
	commit ucitrack
EOF

# 设置权限
chmod 755 /etc/init.d/nezha-agent 2>/dev/null

# 删除缓存
rm -rf /tmp/luci-indexcache /tmp/luci-modulecache/*

exit 0
