#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-ucitrack.json" ] && {
    cat > /usr/share/ucitrack/luci-app-ucitrack.json << EEOF
{
    "config": "ucitrack",
    "init": "ucitrack"
}
EEOF
}
rm -f /tmp/luci-indexcache
#uci track
cfg_id=$(uci add ucitrack fogvdn)
uci set ucitrack.$cfg_id.init="fogvdn"
uci commit ucitrack
exit 0
