#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-kodexplorer.json" ] && {
    cat > /usr/share/ucitrack/luci-app-kodexplorer.json << EEOF
{
    "config": "kodexplorer",
    "init": "kodexplorer"
}
EEOF
}
/etc/init.d/ucitrack reload

uci -q batch <<-EOF >/dev/null
EOF

/etc/init.d/php8-fpm stop
/etc/init.d/php8-fpm disable
rm -rf /tmp/luci-*cache
exit 0
