#!/bin/sh /etc/rc.common


START=95
USE_PROCD=1
NAME=nbtverify
PROG=/usr/bin/nbtverify
PIDFILE=/var/run/nbtverify.pid

xappend() { param="$param $1"; }

append_parm() {
    local section="$1"
    local option="$2"
    local switch="$3"
    local default="$4"
    local _tmp
    config_get _tmp "$section" "$option" "$default"
    [[ -z "$_tmp" ]] && return
    [[ x$default = x && x$_tmp = x0 ]] && return
    [[ x$default = x && x$_tmp = x1 ]] && xappend "$switch" || xappend "$switch=$_tmp"
}

start_instance() {
    local cfg="$1" param
    config_get_bool enabled $cfg enabled 0
    [[ x$enabled = x1 ]] || return 1
    append_parm "$cfg" 'username' '-u' '0'
    append_parm "$cfg" 'password' '-p' '0'
    append_parm "$cfg" 'mobile' '-mobile' '0'
    mkdir -p /var/nbtverify
    xappend "-url /var/nbtverify/url.txt"
    touch /var/nbtverify/url.txt
    xappend "-s /var/log/nbtverify.log"
    touch /var/log/nbtverify.log
    procd_open_instance
    echo ${PROG} ${param}
    ${PROG} ${param}
    xappend "service"
    procd_set_param command ${PROG} ${param}
    procd_set_param respawn
    procd_set_param pidfile $PIDFILE
    procd_close_instance
}

start_service() {
    config_load 'nbtverify'
    config_foreach start_instance 'server'
}

service_triggers() {
    procd_add_reload_trigger "nbtverify"
}

stop_service() {
    killall -q ${PROG}
}
