#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-fullconenat.json" ] && {
    cat > /usr/share/ucitrack/luci-app-fullconenat.json << EEOF
{
    "config": "fullconenat",
    "init": "fullconenat"
}
EEOF
/etc/init.d/ucitrack reload
}

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@fullconenat[-1]
	add ucitrack fullconenat
	set ucitrack.@fullconenat[-1].init=fullconenat
	commit ucitrack
EOF

/etc/init.d/fullconenat enable

rm -f /tmp/luci-indexcache
exit 0
