#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-droidnet.json" ] && {
    cat > /usr/share/ucitrack/luci-app-droidnet.json << EEOF
{
    "config": "droidnet",
    "init": "droidnet"
}
EEOF
}
uci -q batch <<-EOF >/dev/null
EOF
rm -rf /tmp/luci*
exit 0
