#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-lingti.json" ] && {
    cat > /usr/share/ucitrack/luci-app-lingti.json << EEOF
{
    "config": "lingti",
    "init": "lingti"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
EOF

rm -f /tmp/luci-indexcache
exit 0
