#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-shadowsocks-libev.json" ] && {
    cat > /usr/share/ucitrack/luci-app-shadowsocks-libev.json << EEOF
{
    "config": "shadowsocks-libev",
    "init": "shadowsocks-libev"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@shadowsocks-libev[-1]
	add ucitrack shadowsocks-libev
	set ucitrack.@shadowsocks-libev[-1].init=shadowsocks-libev
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
