#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-shadowsocks-libev.json" ] && {
    cat > /usr/share/ucitrack/luci-app-shadowsocks-libev.json << EEOF
{
    "config": "shadowsocks-libev",
    "init": "shadowsocks-libev"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
EOF

rm -f /tmp/luci-indexcache
exit 0
