#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-verysync.json" ] && {
    cat > /usr/share/ucitrack/luci-app-verysync.json << EEOF
{
    "config": "verysync",
    "init": "verysync"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@verysync[-1]
	add ucitrack verysync
	set ucitrack.@verysync[-1].init=verysync
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
