#!/bin/sh
chmod +x  /etc/init.d/kucat

[ -s /etc/config/kucat ] || {
cat <<-EOF > /etc/config/kucat
 
config basic
	option gouser 'kucat-config'
	option gohome 'overview'
	option setbar '1'
	option wizard '0'
	option bgqs '1'
	option gossr 'passwall'
	option dayword '0'
	option background '0'
	option bklock '1'
	option mode 'auto'
	option bkuse '1'
	option primary_rgbs_ts '0'
	option primary_rgbbody '244,245,247'
	option primary_opacity '10'
	option primary_rgbs '55,103,128'
	option primary_rgbm_ts '0.5'
	option primary_rgbm '20,109,179'
	option fontmode '0'
	option font_d '1rem'
	option font_z '0.875rem'
	option font_x '0.82rem'
	option tsoset '1'
	option dhcp_domain '1'

config theme
	option primary_rgbbody '33,45,60'
	option primary_rgbs '76,157,69'
	option remarks '隔栏经典蓝色'
	option primary_opacity '0'
	option primary_rgbm_ts '0.9'
	option bkuse '1'
	option primary_rgbs_ts '0.1'
	option mode 'auto'
	option use '0'
	option primary_rgbm 'blue'

config theme
	option primary_rgbbody '33,45,60'
	option primary_rgbs '76,157,69'
	option primary_rgbm_ts '0.9'
	option primary_opacity '0'
	option bkuse '0'
	option remarks '无隔栏清爽绿'
	option primary_rgbs_ts '0'
	option mode 'auto'
	option use '0'
	option primary_rgbm 'green'

config theme
	option primary_rgb_ts '0.3'
	option primary_rgbm '26,131,97'
	option primary_rgbs '76 157 69'
	option bkuse '0'
	option remarks '无隔栏绿模糊'
	option primary_rgbs_ts '0'
	option primary_opacity '10'
	option primary_rgbm_ts '0.5'
	option mode 'light'
	option use '0'

config theme
	option primary_rgbm '20,109,179'
	option primary_rgbs 'rgb(55,103,128)'
	option mode 'auto'
	option primary_opacity '10'
	option primary_rgbs_ts '0'
	option primary_rgbm_ts '0.5'
	option remarks '无隔栏蓝模糊'
	option bkuse '1'
	option use '1'

config theme
	option primary_rgbm '50 67 77'
	option primary_rgbs 'rgb(64, 68, 70)'
	option primary_opacity '0'
	option primary_rgbs_ts '0'
	option remarks '灰无隔栏无背景'
	option bkuse '0'
	option primary_rgbm_ts '0.9'
	option mode 'auto'
	option use '0'

config theme
	option bkuse '1'
	option mode 'dark'
	option primary_rgbm '50 66 77'
	option primary_rgbs '55 80 90'
	option remarks '炫灰隔栏模糊'
	option primary_rgbs_ts '0.1'
	option use '0'
	option primary_rgbm_ts '0.5'
	option primary_opacity '10'

config theme
	option mode 'light'
	option primary_rgbm '74,161,133'
	option primary_rgbs '76 157 69'
	option primary_rgbs_ts '0.1'
	option remarks '炫绿隔栏模糊'
	option primary_rgbm_ts '0.7'
	option bkuse '1'
	option primary_opacity '10'
	option use '0'



EOF

}


rm -f /tmp/luci-indexcache
exit 0
