#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-homebridge.json" ] && {
    cat > /usr/share/ucitrack/luci-app-homebridge.json << EEOF
{
    "config": "homebridge",
    "init": "homebridge"
}
EEOF
}
uci -q batch <<-EOF >/dev/null
EOF
exit 0
