#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-netkeeper-interception.json" ] && {
    cat > /usr/share/ucitrack/luci-app-netkeeper-interception.json << EEOF
{
    "config": "netkeeper-interception",
    "init": "netkeeper-interception"
}
EEOF
/etc/init.d/ucitrack reload
}
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@netkeeper-interception[-1]
	add ucitrack netkeeper-interception
	set ucitrack.@netkeeper-interception[-1].init="netkeeper-interception"
	commit ucitrack
EOF
rm -rf /var/luci-modulecache/; rm -f /var/luci-indexcache;
exit 0

