#!/bin/sh /etc/rc.common

# Copyright 2020 BlackYau <blackyau426@gmail.com>
# GNU General Public License v3.0

LOG_PATH="/usr/lib/suselogin"
LOG_FILE="/tmp/log/suselogin/login.log"
SCRIPT_NAME="login.sh"
SCRIPT="$LOG_PATH/$SCRIPT_NAME"

log() {
	echo "$(date "+%Y-%m-%d %H:%M:%S"): $1"
}

start() {

	{
		mkdir -p /tmp/log/suselogin
	} >$LOG_FILE

	if pgrep -f "$SCRIPT" >/dev/null; then
		log "已启动，准备重新启动"
		restart
	else
		$SCRIPT &
		log "已启动"
	fi
}

stop() {
	if pgrep -f "$SCRIPT" >/dev/null; then
		kill $(pgrep -f "$SCRIPT") 2>/dev/null
		log "已停止"
	else
		log "服务未运行"
	fi
}

restart() {
	stop
	sleep 1
	start
}

disable() {
	if [ -d /tmp/log/suselogin ]; then
		rm -rf /tmp/log/suselogin/*
		log "已清空日志"
	else
		log "日志目录不存在"
	fi
}
