#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-v2ray_server.json" ] && {
    cat > /usr/share/ucitrack/luci-app-v2ray_server.json << EEOF
{
    "config": "v2ray_server",
    "init": "v2ray_server"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
	delete firewall.v2ray_server
	set firewall.v2ray_server=include
	set firewall.v2ray_server.type=script
	set firewall.v2ray_server.path=/var/etc/v2ray_server.include
	set firewall.v2ray_server.reload=1
	commit firewall
EOF

uci -q batch <<-EOF >/dev/null
EOF

rm -rf /tmp/luci-*cache
exit 0
