#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-n2n.json" ] && {
    cat > /usr/share/ucitrack/luci-app-n2n.json << EEOF
{
    "config": "n2n",
    "init": "n2n"
}
EEOF
/etc/init.d/ucitrack reload
}

uci -q batch <<-EOF >/dev/null
EOF

rm -f /tmp/luci-indexcache
exit 0
