include $(TOPDIR)/rules.mk

PKG_VERSION:=2.0.0-21_cn_sky
PKG_RELEASE:=12

LUCI_TITLE:=LuCI support for Frpc
LUCI_DEPENDS:=+libc +frpc
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
