#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-wizard.json" ] && {
    cat > /usr/share/ucitrack/luci-app-wizard.json << EEOF
{
    "config": "wizard",
    "init": "wizard"
}
EEOF
}
/etc/init.d/ucitrack reload

touch /etc/config/wizard

uci -q batch <<-EOF >/dev/null
EOF

chmod +x /etc/init.d/wizard 2>/dev/null
rm -f /tmp/luci-indexcache

exit 0
