#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-modem.json" ] && {
    cat > /usr/share/ucitrack/luci-app-modem.json << EEOF
{
    "config": "modem",
    "init": "modem"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@modem[-1]
	add ucitrack modem
	set ucitrack.@modem[-1].init=modem
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
