#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-modem.json" ] && {
    cat > /usr/share/ucitrack/luci-app-modem.json << EEOF
{
    "config": "modem",
    "init": "modem"
}
EEOF
/etc/init.d/ucitrack reload
}

uci -q batch <<-EOF >/dev/null
EOF

rm -f /tmp/luci-indexcache
exit 0
