#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-weburl.json" ] && {
    cat > /usr/share/ucitrack/luci-app-weburl.json << EEOF
{
    "config": "weburl",
    "init": "weburl"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@weburl[-1]
	add ucitrack weburl
	set ucitrack.@weburl[-1].init=weburl
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
