#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-dnsmasq-ipset.json" ] && {
    cat > /usr/share/ucitrack/luci-app-dnsmasq-ipset.json << EEOF
{
    "config": "dnsmasq-ipset",
    "init": "dnsmasq-ipset"
}
EEOF
}
uci -q batch <<-EOF >/dev/null
EOF
exit 0
