#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-dnsmasq-ipset.json" ] && {
    cat > /usr/share/ucitrack/luci-app-dnsmasq-ipset.json << EEOF
{
    "config": "dnsmasq-ipset",
    "init": "dnsmasq-ipset"
}
EEOF
}
uci -q batch <<-EOF >/dev/null
    delete ucitrack.@dnsmasq-ipset[-1]
    add ucitrack dnsmasq-ipset
    set ucitrack.@dnsmasq-ipset[-1].init=dnsmasq-ipset
    commit ucitrack
EOF
exit 0
