#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-autoipsetadder.json" ] && {
    cat > /usr/share/ucitrack/luci-app-autoipsetadder.json << EEOF
{
    "config": "autoipsetadder",
    "init": "autoipsetadder"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@autoipsetadder[-1]
	add ucitrack autoipsetadder
	set ucitrack.@autoipsetadder[-1].init=autoipsetadder
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
