#!/bin/sh
#
# This script is run by the pppd after the link is established.
# It should be used to add routes, set IP address, run the mailq etc.
#
# This script is called with the following arguments:
# Arg  Name               Example
# $1   Interface name     ppp0
# $2   The tty            ttyS1
# $3   The link speed     38400
# $4   Local IP number    12.34.56.78
# $5   Peer  IP number    12.34.56.99
#

#
# The environment is cleared before executing this script
# so the path must be reset
#
PATH=/usr/sbin:/sbin:/usr/bin:/bin
export PATH

# Loop through all files in the ip-up.d directory and execute them if they are executable
IP_UP_D_DIR="/etc/ppp/ip-up.d"
for script in "$IP_UP_D_DIR"/*; do
    if [ -x "$script" ]; then
        "$script" "$@"
    fi
done

exit 0
