#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-dnspod.json" ] && {
    cat > /usr/share/ucitrack/luci-app-dnspod.json << EEOF
{
    "config": "dnspod",
    "init": "dnspod"
}
EEOF
}
/etc/init.d/ucitrack reload

uci -q batch <<-EOF >/dev/null
EOF


/etc/init.d/dnspod stop

rm -f /tmp/luci-indexcache
exit 0
