#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-timecontrol.json" ] && {
    cat > /usr/share/ucitrack/luci-app-timecontrol.json << EEOF
{
    "config": "timecontrol",
    "init": "timecontrol"
}
EEOF
/etc/init.d/ucitrack reload
}

uci -q batch <<-EOF >/dev/null
	delete firewall.timecontrol
	set firewall.timecontrol=include
	set firewall.timecontrol.type=script
	set firewall.timecontrol.path=/var/etc/timecontrol.include
	set firewall.timecontrol.reload=1
EOF

uci -q batch <<-EOF >/dev/null
EOF

rm -rf /tmp/luci-*cache
exit 0
