# Cellular status

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Cellular Network Dashboard
LUCI_DEPENDS:=+uqmi

PKG_LICENSE:=GPLv3
PKG_VERSION:=1.0.1
PKG_RELEASE:=3

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
