include $(TOPDIR)/rules.mk

LUCI_TITLE:=LingTi Game Acc
LUCI_DEPENDS:=+lingtigameacc +luci-base
LUCI_PKGARCH:=all


include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
