#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

PROG=/usr/bin/nginx-ui
CONF=/etc/nginx-ui/app.ini

get_config() {
    config_get_bool enabled $1 enabled 0
    config_get port $1 port 9000
    config_get host $1 host 0.0.0.0
}

start_service() {
    config_load nginx-ui
    config_foreach get_config nginx-ui
    
    [ "$enabled" -eq 0 ] && return 1
	
	if [ -f "$CONF" ]; then
		sed -i "s/^Port = .*/Port = $port/" "$CONF"
		sed -i "s/^Host = .*/Host = $host/" "$CONF"
	else
		mkdir -p "${CONF%/*}"
		cat > "$CONF" <<-EOF
		[server]
		RunMode  = release
		Port = $port
		Host = $host
		EOF
	fi
    
    procd_open_instance
    procd_set_param command $PROG
	procd_append_param command -config "$CONF"
    procd_set_param stderr 1
    procd_set_param stdout 1
    procd_set_param respawn
    procd_close_instance
}

service_triggers() {
    procd_add_reload_trigger "nginx-ui"
}
