#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-pingos.json" ] && {
    cat > /usr/share/ucitrack/luci-app-pingos.json << EEOF
{
    "config": "pingos",
    "init": "pingos"
}
EEOF
/etc/init.d/ucitrack reload
}

uci -q batch <<-EOF >/dev/null
EOF

rm -rf /tmp/luci-*cache
exit 0
