#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-easytier.json" ] && {
    cat > /usr/share/ucitrack/luci-app-easytier.json << EEOF
{
    "config": "easytier",
    "init": "easytier"
}
EEOF
}
/etc/init.d/ucitrack reload

uci -q batch <<-EOF >/dev/null
EOF
chmod +x /etc/init.d/easytier
rm -rf /tmp/luci-indexcache /tmp/luci-modulecache
exit 0
