#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-filebrowser.json" ] && {
    cat > /usr/share/ucitrack/luci-app-filebrowser.json << EEOF
{
    "config": "filebrowser",
    "init": "filebrowser"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
EOF

rm -f /tmp/luci-indexcache
exit 0
