#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-vnt.json" ] && {
    cat > /usr/share/ucitrack/luci-app-vnt.json << EEOF
{
    "config": "vnt",
    "init": "vnt"
}
EEOF
}
/etc/init.d/ucitrack reload

uci -q batch <<-EOF >/dev/null
EOF
chmod +x /etc/init.d/vnt
rm -rf /tmp/luci-indexcache /tmp/luci-modulecache
exit 0
