#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-amlogic.json" ] && {
    cat > /usr/share/ucitrack/luci-app-amlogic.json << EEOF
{
    "config": "amlogic",
    "init": "amlogic"
}
EEOF
/etc/init.d/ucitrack reload
}

sed -i 's/cbi.submit\"] = true/cbi.submit\"] = \"1\"/g' /usr/lib/lua/luci/dispatcher.lua

uci -q batch <<-EOF >/dev/null
EOF

rm -rf /tmp/luci-*
exit 0
