#!/bin/sh /etc/rc.common

START=99
STOP=15
USE_PROCD=1

SERVICE=clouddrive2
PROGDIR=/usr/share/clouddrive2/clouddrive

service_triggers() {
	procd_add_reload_trigger "clouddrive2"
}

start_service() {
    procd_open_instance
    procd_set_param command "$PROGDIR"
    procd_set_param respawn
    procd_close_instance
    echo "$SERVICE" started
}

stop_service() {
    echo stop "$SERVICE"
    pgrep $PROGDIR | xargs kill -9
}
