#!/bin/sh
#
# This script is run by the pppd after the link is established.
# It should be used to add routes, set IP address, run the mailq
# etc.
#
# This script is called with the following arguments:
#    Arg  Name               Example
#    $1   Interface name     ppp0
#    $2   The tty            ttyS1
#    $3   The link speed     38400
#    $4   Local IP number    12.34.56.78
#    $5   Peer  IP number    12.34.56.99
#

#
# The  environment is cleared before executing this script
# so the path must be reset
#
PATH=/usr/sbin:/sbin:/usr/bin:/bin
export PATH

QUIT_TIME="$(date "+%Y-%m-%d_%H:%M:%S")"
USERNAME="${PEERNAME}"
PEERIP="${5}"

USER_CONFIG="pppoe-user"
USER_CFGID="$(uci show ${USER_CONFIG} | grep "${USERNAME}" | cut -d '.' -sf 2)"
UP="upload"
DOWN="download"
UPLOAD_HANDLE="$(nft -a list chain inet pppoe-user-qos ${UP} | grep "${PEERIP}" | awk '{print $NF}')"
DOWNLOAD_HANDLE="$(nft -a list chain inet pppoe-user-qos ${DOWN} | grep "${PEERIP}" | awk '{print $NF}')"

nft delete rule inet pppoe-user-qos ${UP} handle "${UPLOAD_HANDLE}"
nft delete rule inet pppoe-user-qos ${DOWN} handle "${DOWNLOAD_HANDLE}"

logger "${QUIT_TIME} ${PEERNAME} ${PEERIP} SPEED-LIMIT >>>>>> The script has been executed!"

exit 0
