#!/bin/sh 
[ ! -f "/usr/share/ucitrack/luci-app-aliddns.json" ] && {
    cat > /usr/share/ucitrack/luci-app-aliddns.json << EEOF
{
    "config": "aliddns",
    "init": "aliddns"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@aliddns[-1]
	add ucitrack aliddns
	set ucitrack.@aliddns[-1].init=aliddns
	commit ucitrack
EOF

exit 0
