 
include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-nginx
PKG_VERSION:=20230323
PKG_RELEASE:=2
PKG_ARCH:=all
PKG_MAINTAINER:=Zhang Hua <zhanghuadedn@gmail.com>
PKG_LICENSE:=WTFPL

LUCI_TITLE:=LuCI app for Nginx
LUCI_DEPENDS:=+nginx

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
