#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-lucky.json" ] && {
    cat > /usr/share/ucitrack/luci-app-lucky.json << EEOF
{
    "config": "lucky",
    "init": "lucky"
}
EEOF
}
/etc/init.d/ucitrack reload

uci -q batch <<-EOF >/dev/null
EOF
[[ -f /etc/config/lucky ]] || echo "config lucky 'lucky' " > /etc/config/lucky
rm -rf /tmp/luci*
exit 0
