#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-lucky.json" ] && {
    cat > /usr/share/ucitrack/luci-app-lucky.json << EEOF
{
    "config": "lucky",
    "init": "lucky"
}
EEOF
}

[ -f "/etc/config/ucitrack" ] && {
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@lucky[-1]
	add ucitrack lucky
	set ucitrack.@lucky[-1].init=lucky
	commit ucitrack
EOF
}

rm -rf /tmp/luci-*
exit 0