include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-minieap
PKG_MAINTAINER:=lala <maoerpet@foxmail.com>

LUCI_TITLE:=LuCI support for MiniEAP
LUCI_DEPENDS:=+minieap
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
