#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-coredns.json" ] && {
    cat > /usr/share/ucitrack/luci-app-coredns.json << EEOF
{
    "config": "coredns",
    "init": "coredns"
}
EEOF
}
/etc/init.d/ucitrack reload

uci -q batch <<-EOF >/dev/null
EOF

rm -rf /tmp/luci-*
exit 0
