#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-iperf3-server.json" ] && {
    cat > /usr/share/ucitrack/luci-app-iperf3-server.json << EEOF
{
    "config": "iperf3-server",
    "init": "iperf3-server"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
EOF

exit 0
