#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-airplay2.json" ] && {
    cat > /usr/share/ucitrack/luci-app-airplay2.json << EEOF
{
    "config": "airplay2",
    "init": "airplay2"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@airplay2[-1]
	add ucitrack airplay2
	set ucitrack.@airplay2[-1].init=airplay2
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
