#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-rclone.json" ] && {
    cat > /usr/share/ucitrack/luci-app-rclone.json << EEOF
{
    "config": "rclone",
    "init": "rclone"
}
EEOF
}
/etc/init.d/ucitrack reload

uci -q batch <<-EOF >/dev/null
EOF

rm -f /tmp/luci-indexcache
exit 0
