#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-npc.json" ] && {
    cat > /usr/share/ucitrack/luci-app-npc.json << EEOF
{
    "config": "npc",
    "init": "npc"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@npc[-1]
	add ucitrack npc
	set ucitrack.@npc[-1].init=npc
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
