#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-omr-quota.json" ] && {
    cat > /usr/share/ucitrack/luci-app-omr-quota.json << EEOF
{
    "config": "omr-quota",
    "init": "omr-quota"
}
EEOF
}
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@omr-quota[-1]
	add ucitrack omr-quota
	set ucitrack.@omr-quota[-1].init="omr-quota"
	commit ucitrack
EOF
if [ "$(uci -q get ucitrack.@network[-1].affects | grep omr-quota)" = "" ]; then
	uci -q batch <<-EOF >/dev/null
		add_list ucitrack.@network[-1].affects="omr-quota"
		commit ucitrack
	EOF
fi
exit 0