#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-gost.json" ] && {
    cat > /usr/share/ucitrack/luci-app-gost.json << EEOF
{
    "config": "gost",
    "init": "gost"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
EOF

rm -f /tmp/luci-indexcache
exit 0
