include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.0-20_cn_sky
PKG_RELEASE:=9

LUCI_TITLE:=LuCI support for Frps
LUCI_DEPENDS:=+libc
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
