#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-homeredirect.json" ] && {
    cat > /usr/share/ucitrack/luci-app-homeredirect.json << EEOF
{
    "config": "homeredirect",
    "init": "homeredirect"
}
EEOF
}
/etc/init.d/ucitrack reload

uci -q batch <<-EOF >/dev/null
	delete firewall.homeredirect
	set firewall.homeredirect=include
	set firewall.homeredirect.type=script
	set firewall.homeredirect.path=/etc/homeredirect/firewall.include
	set firewall.homeredirect.reload=1
EOF

uci -q batch <<-EOF >/dev/null
EOF

rm -rf /tmp/luci-*cache
exit 0
