#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-ssr_mudb_server.json" ] && {
    cat > /usr/share/ucitrack/luci-app-ssr_mudb_server.json << EEOF
{
    "config": "ssr_mudb_server",
    "init": "ssr_mudb_server"
}
EEOF
/etc/init.d/ucitrack reload
}

uci -q batch <<-EOF >/dev/null
	delete firewall.ssr_mudb_server
	set firewall.ssr_mudb_server=include
	set firewall.ssr_mudb_server.type=script
	set firewall.ssr_mudb_server.path=/var/etc/ssr_mudb_server.include
	set firewall.ssr_mudb_server.reload=1
EOF

uci -q batch <<-EOF >/dev/null
EOF

chmod a+x /usr/share/ssr_mudb_server/* >/dev/null 2>&1
cp -rf /usr/bin/python3 /usr/bin/python
rm -rf /tmp/luci-*cache
exit 0
