#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-shairplay.json" ] && {
    cat > /usr/share/ucitrack/luci-app-shairplay.json << EEOF
{
    "config": "shairplay",
    "init": "shairplay"
}
EEOF
/etc/init.d/ucitrack reload
}

# needed for "Save and Apply" to restart shairplay
uci -q batch <<-EOF >/dev/null
EOF

rm -f /tmp/luci-indexcache
exit 0
