#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-shairplay.json" ] && {
    cat > /usr/share/ucitrack/luci-app-shairplay.json << EEOF
{
    "config": "shairplay",
    "init": "shairplay"
}
EEOF
}

# needed for "Save and Apply" to restart shairplay
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@shairplay[-1]
	add ucitrack shairplay
	set ucitrack.@shairplay[-1].init="shairplay"
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
