#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-ympd.json" ] && {
    cat > /usr/share/ucitrack/luci-app-ympd.json << EEOF
{
    "config": "ympd",
    "init": "ympd"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
EOF

exit 0
