#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-openai.json" ] && {
    cat > /usr/share/ucitrack/luci-app-openai.json << EEOF
{
    "config": "openai",
    "init": "openai"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@openai[-1]
	add ucitrack openai
	set ucitrack.@openai[-1].init=openai
	commit ucitrack
EOF

rm -rf /tmp/luci-*
exit 0
