#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-openai.json" ] && {
    cat > /usr/share/ucitrack/luci-app-openai.json << EEOF
{
    "config": "openai",
    "init": "openai"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
EOF

rm -rf /tmp/luci-*
exit 0
