#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-nezha-agent.json" ] && {
    cat > /usr/share/ucitrack/luci-app-nezha-agent.json << EEOF
{
    "config": "nezha-agent",
    "init": "nezha-agent"
}
EEOF
}
/etc/init.d/ucitrack reload

uci -q batch <<-EOF >/dev/null
EOF

rm -f /tmp/luci-indexcache
exit 0
