include $(TOPDIR)/rules.mk

PKG_VERSION:=1.23.3
PKG_RELEASE:=29

LUCI_TITLE:=LuCI Support for nikki
LUCI_DEPENDS:=+luci-base +nikki

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature