#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-uugamebooster.json" ] && {
    cat > /usr/share/ucitrack/luci-app-uugamebooster.json << EEOF
{
    "config": "uugamebooster",
    "init": "uugamebooster"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
EOF

rm -f /tmp/luci-indexcache
exit 0
