#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-uuplugin.json" ] && {
    cat > /usr/share/ucitrack/luci-app-uuplugin.json << EEOF
{
    "config": "uuplugin",
    "init": "uuplugin"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@uuplugin[-1]
	add ucitrack uuplugin
	set ucitrack.@uuplugin[-1].init=uuplugin
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
