#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-gpioled.json" ] && {
    cat > /usr/share/ucitrack/luci-app-gpioled.json << EEOF
{
    "config": "gpioled",
    "init": "gpioled"
}
EEOF
}
uci -q batch <<-EOF >/dev/null
EOF
rm -rf /tmp/luci*
exit 0
