include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for Nginx UI
LUCI_DEPENDS:=+nginx-ui +luci-base
LUCI_PKGARCH:=all

PKG_VERSION:=1.0.0
PKG_RELEASE:=4

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
