#!/bin/sh 
[ ! -f "/usr/share/ucitrack/luci-app-qos-emong.json" ] && {
    cat > /usr/share/ucitrack/luci-app-qos-emong.json << EEOF
{
    "config": "qos-emong",
    "init": "qos-emong"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
          delete ucitrack.@qos-emong[-1]
          add ucitrack qos-emong
          set ucitrack.@qos-emong[-1].init=qos-emong
          commit ucitrack
EOF
rm -f /tmp/luci-indexcahe
exit 0
