#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-autoupdate.json" ] && {
    cat > /usr/share/ucitrack/luci-app-autoupdate.json << EEOF
{
    "config": "autoupdate",
    "init": "autoupdate"
}
EEOF
}
/etc/init.d/ucitrack reload

uci -q batch <<-EOF >/dev/null
EOF

exit 0
