#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-syncthing.json" ] && {
    cat > /usr/share/ucitrack/luci-app-syncthing.json << EEOF
{
    "config": "syncthing",
    "init": "syncthing"
}
EEOF
}
/etc/init.d/ucitrack reload
touch /etc/config/syncthing

sed -i "s/127.0.0.1:8384/0.0.0.0:8384/" /etc/config/syncthing
uci -q batch <<-EOF >/dev/null
EOF
# remove LuCI cache
rm -f /tmp/luci*
exit 0
