#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-natter.json" ] && {
    cat > /usr/share/ucitrack/luci-app-natter.json << EEOF
{
    "config": "natter",
    "init": "natter"
}
EEOF
/etc/init.d/ucitrack reload
}

uci -q batch <<-EOF >/dev/null
	
	delete firewall.natter
	set firewall.natter=include
	set firewall.natter.type=script
	set firewall.natter.path=/var/etc/natter.include
	set firewall.natter.reload=1
	commit firewall
EOF

exit 0
