#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-usbmodem.json" ] && {
    cat > /usr/share/ucitrack/luci-app-usbmodem.json << EEOF
{
    "config": "usbmodem",
    "init": "usbmodem"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@usbmodem[-1]
	add ucitrack usbmodem
	set ucitrack.@usbmodem[-1].init=usbmodem
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
