#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-usbmodem.json" ] && {
    cat > /usr/share/ucitrack/luci-app-usbmodem.json << EEOF
{
    "config": "usbmodem",
    "init": "usbmodem"
}
EEOF
}
/etc/init.d/ucitrack reload

uci -q batch <<-EOF >/dev/null
EOF

rm -f /tmp/luci-indexcache
exit 0
