#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-minieap.json" ] && {
    cat > /usr/share/ucitrack/luci-app-minieap.json << EEOF
{
    "config": "minieap",
    "init": "minieap"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@minieap[-1]
	add ucitrack minieap
	set ucitrack.@minieap[-1].init=minieap
	commit ucitrack
EOF

rm -rf /tmp/luci-*
exit 0
