#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-easyupdate.json" ] && {
    cat > /usr/share/ucitrack/luci-app-easyupdate.json << EEOF
{
    "config": "easyupdate",
    "init": "easyupdate"
}
EEOF
}
/etc/init.d/ucitrack reload

uci -q batch <<-EOF >/dev/null
EOF

rm -f /tmp/luci-indexcache
exit 0
