#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-autorepeater.json" ] && {
    cat > /usr/share/ucitrack/luci-app-autorepeater.json << EEOF
{
    "config": "autorepeater",
    "init": "autorepeater"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
EOF

rm -f /tmp/luci-indexcache
exit 0
