#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-ps3netsrv.json" ] && {
    cat > /usr/share/ucitrack/luci-app-ps3netsrv.json << EEOF
{
    "config": "ps3netsrv",
    "init": "ps3netsrv"
}
EEOF
}
/etc/init.d/ucitrack reload

uci -q batch <<-EOF >/dev/null
EOF

rm -f /tmp/luci-indexcache
exit 0
