#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-pcimodem.json" ] && {
    cat > /usr/share/ucitrack/luci-app-pcimodem.json << EEOF
{
    "config": "pcimodem",
    "init": "pcimodem"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
EOF

rm -f /tmp/luci-indexcache
exit 0
