#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-frpc.json" ] && {
    cat > /usr/share/ucitrack/luci-app-frpc.json << EEOF
{
    "config": "frpc",
    "init": "frpc"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@frpc[-1]
	add ucitrack frpc
	set ucitrack.@frpc[-1].init=frpc
	commit ucitrack
EOF

rm -rf /tmp/luci-indexcache /tmp/luci-modulecache
exit 0
