#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@frp[-1]
	add ucitrack frp
	set ucitrack.@frp[-1].init=frp
	commit ucitrack
EOF

grep -q "frp 'common'" /etc/config/frpc || cp -f etc/config/frpc-opkg /etc/config/frpc

rm -f /tmp/luci-indexcache
exit 0
