#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-frp.json" ] && {
    cat > /usr/share/ucitrack/luci-app-frp.json << EEOF
{
    "config": "frp",
    "init": "frp"
}
EEOF
}
/etc/init.d/ucitrack reload

uci -q batch <<-EOF >/dev/null
EOF

rm -f /tmp/luci-indexcache
exit 0
