#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-luci-fan.json" ] && {
    cat > /usr/share/ucitrack/luci-app-luci-fan.json << EEOF
{
    "config": "luci-fan",
    "init": "luci-fan"
}
EEOF
}
/etc/init.d/ucitrack reload

/usr/libexec/fan-control init

uci -q batch <<-EOF >/dev/null
EOF

exit 0
