#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-unblockmusic.json" ] && {
    cat > /usr/share/ucitrack/luci-app-unblockmusic.json << EEOF
{
    "config": "unblockmusic",
    "init": "unblockmusic"
}
EEOF
/etc/init.d/ucitrack reload
}

uci -q batch <<-EOF >/dev/null

	delete firewall.unblockmusic
	set firewall.unblockmusic=include
	set firewall.unblockmusic.type=script
	set firewall.unblockmusic.path=/var/etc/unblockmusic.include
	set firewall.unblockmusic.reload=1
	commit firewall
EOF

rm -f /tmp/luci-indexcache
exit 0
