#!/bin/sh
grep -q "sample_config" /etc/config/zerotier || cp -f /etc/config/zerotier-opkg /etc/config/zerotier

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@zerotier[-1]
	commit ucitrack

	delete firewall.zerotier
	commit firewall
EOF

rm -f /tmp/luci-indexcache
exit 0
