#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-xray_core.json" ] && {
    cat > /usr/share/ucitrack/luci-app-xray_core.json << EEOF
{
    "config": "xray_core",
    "init": "xray_core"
}
EEOF
}
/etc/init.d/ucitrack reload
uci get xray_core.@general[-1] >/dev/null 2>&1 || uci add xray_core general >/dev/null 2>&1
uci commit xray_core
uci -q batch <<-EOF >/dev/null
EOF
exit 0
