#!/bin/sh /etc/rc.common

START=99
STOP=10

USE_PROCD=1
PROG="/usr/bin/nginx-ui"
ARGS="-config /etc/nginx-ui/app.ini >/var/log/nginx/nginx-ui.log 2>&1"

start_service() {
    procd_open_instance
    procd_set_param command "$PROG" $ARGS
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn
    procd_close_instance
}

stop_service() {
    killall nginx-ui
}

restart() {
    stop
    start
}
