#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-guest-wifi.json" ] && {
    cat > /usr/share/ucitrack/luci-app-guest-wifi.json << EEOF
{
    "config": "guest-wifi",
    "init": "guest-wifi"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@guest-wifi[-1]
	add ucitrack guest-wifi
	set ucitrack.@guest-wifi[-1].init=guest-wifi
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0