#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-parentcontrol.json" ] && {
    cat > /usr/share/ucitrack/luci-app-parentcontrol.json << EEOF
{
    "config": "parentcontrol",
    "init": "parentcontrol"
}
EEOF
/etc/init.d/ucitrack reload
}

uci -q batch <<-EOF >/dev/null
EOF

uci -q delete firewall.parentcontrol
uci -q set firewall.parentcontrol=include
uci -q set firewall.parentcontrol.type=script
uci -q set firewall.parentcontrol.path=/etc/parentcontrol.include
uci -q set firewall.parentcontrol.reload=1
uci commit firewall
rm -f /tmp/luci-indexcache
exit 0
